[package]
name = "DiscordAnilistBot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.14"
serde_json = "1.0.93"
serenity = "0.11.5"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
