[package]
name = "kasuki"
version = "2.8.0"
edition = "2021"
authors = ["Valgul <contact@valgul.moe>"]
description = "A discord bot written in rust that get info from anilist API"
readme = "readme.md"
repository = "https://github.com/ValgulNecron/kasuki"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["json", "multipart"] }
serde = "1.0.197"
serde_json = "1.0.115"
serenity = { version = "0.12.1", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "utils", "full"] }
tokio = { version = "1.36.0", features = ["full"] }
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio-native-tls", "postgres"] }
rand = "0.9.0-alpha.1"
chrono = "0.4.35"
uuid = { version = "1.8.0", features = ["v4"] }
dotenv = "0.15.0"
image = "0.25.0"
base64 = "0.22.0"
tracing = { version = "0.1.40" }
once_cell = "1.19.0"
tracing-subscriber = { version = "0.3.18", features = ["default", "env-filter"] }
tracing-core = "0.1.32"
serde_with = { version = "3.7.0", features = ["macros"] }
rust-fuzzy-search = "0.1.1"
palette = "0.7.5"
catbox = "0.8.2"
imgurs = "0.11.2"
tracing-appender = "0.2.3"
tonic = "0.11.0"
prost = "0.12.3"
tonic-reflection = "0.11.0"
ratatui = "0.26.2"
crossterm = "0.27.0"
sysinfo = "0.30.11"
tui-logger = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"

[profile.dev]
codegen-units = 512


[profile.release]
lto = true
codegen-units = 8
