[package]
name = "kasuki"
version = "1.0.0"
edition = "2021"
authors = ["Valgul <contact@valgul.moe>"]
description = "A discord bot written in rust that get info from anilist API"
readme = "readme.md"
repository = "https://github.com/ValgulNecron/kasuki"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
reqwest = "0.11.2"
serde = "1.0.192"
serde_json = "1.0.108"
serenity = { version = "0.11.7", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "utils"] }
tokio = { version = "1.32.0", features = ["full"] }
sqlx = { version = "0.7.2", features = ["sqlite", "runtime-tokio-native-tls"] }
rand = "0.8.5"
chrono = "0.4.31"
uuid = { version = "1.5.0", features = ["v4"] }
dotenv = "0.15.0"
image = "0.24.7"
base64 = "0.21.5"
log = { version = "0.4.20" }
colored = "2.0.4"


[profile.release]
lto = true
