[package]
name = "kasuki"
version = "1.0.0"
edition = "2021"
authors = ["Valgul <contact@valgul.moe>"]
description = "A discord bot written in rust that get info from anilist API"
readme = "readme.md"
repository = "https://github.com/ValgulNecron/kasuki"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.3"
reqwest = { version = "0.11.23", features = ["json"] }
serde = "1.0.195"
serde_json = "1.0.111"
serenity = { version = "0.12.0", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "utils", "full"] }
tokio = { version = "1.35.1", features = ["full"] }
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio-native-tls", "postgres"] }
rand = "0.8.5"
chrono = "0.4.33"
uuid = { version = "1.7.0", features = ["v4"] }
dotenv = "0.15.0"
image = "0.24.8"
base64 = "0.21.7"
tracing = { version = "0.1.40" }
once_cell = "1.19.0"
tracing-subscriber = { version = "0.3.18", features = ["default", "env-filter"] }
tracing-core = "0.1.32"
log = "0.4.20"
serde_with = { version = "3.5.1", features = ["macros"] }
rust-fuzzy-search = "0.1.1"
palette = "0.7.3"
catbox = "0.8.2"
imgur = "0.7.0"

[profile.dev]
codegen-units = 512


[profile.release]
lto = true
incremental = true
codegen-units = 8
