version: '3'
services:
  rust_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_TOKEN=your_discord_token_here
      - AI_API_TOKEN=your_token_here_for_the_ai_part
      - AI_API_BASE_URL=the_url_for_the_request_open_ai_or_any_openai_proxy_one