version: '3'
services:
  kasuki:
    # let you build with the git file you have cloned (there is no guaranteed on a working states)
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: valgul/kasuki:latest # the latest stable version of kasuki
    # image: valgul/kasuki:dev # the latest dev build that compile there could be error.
    container_name: kasuki
    restart: unless-stopped
    tty: true
    ports:
      - "443:443"
    volumes:
      - ./db/:/kasuki/db
      - ./logs/:/kasuki/logs/
      - ./server_image:/kasuki/server_image/
      - ./cert:/kasuki/cert/
      - ./new_member_image:/kasuki/new_member_image
      - ./config.toml:/kasuki/config.toml
      - /etc/localtime:/etc/localtime:ro

