[package]
name = "kasuki"
version = "2.10.7"
edition = "2021"
authors = ["Valgul <contact@valgul.moe>"]
description = "A discord bot written in rust that get info from anilist API"
readme = "../readme.md"
repository = "https://github.com/ValgulNecron/kasuki"
license-file = "../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.6"
reqwest = { version = "0.12.7", features = ["json", "multipart", "blocking"] }
serde = "1.0.209"
serde_json = "1.0.127"
serenity = { git = "https://github.com/serenity-rs/serenity.git", branch = "current", default-features = false, features = ["gateway", "rustls_backend", "model", "utils", "full", "unstable_discord_api", "voice", "cache", "http"] }
tokio = { version = "1.39.3", features = ["full"] }
rand = "0.9.0-alpha.2"
chrono = "0.4.38"
uuid = { version = "1.10.0", features = ["v4"] }
image = "0.25.2"
base64 = "0.22.1"
tracing = { version = "0.1.40" }
once_cell = "1.19.0"
tracing-subscriber = { version = "0.3.18", features = ["default", "env-filter"] }
serde_with = { version = "3.9.0", features = ["macros"] }
rust-fuzzy-search = "0.1.1"
palette = "0.7.6"
tracing-appender = "0.2.3"
tonic = { version = "0.12.2", features = ["tls"] }
prost = "0.13.1"
tonic-reflection = "0.12.2"
sysinfo = "0.31.3"
rayon = "1.10.0"
os_info = "3.8.2"
rcgen = "0.13.1"
markdown_converter = "0.3.4"
futures = "0.3.30"
rapidfuzz = "0.5.0"
cynic = { version = "3.7.3", features = ["reqwest", "http-reqwest", "serde_json"] }
moka = { version = "0.12.8", features = ["future"] }
toml = "0.8.19"
num-bigint = "0.4.6"
text-to-png = "0.2.0"
songbird = { git = "https://github.com/ValgulNecron/songbird.git", branch = "next", features = ["serenity", "rustls", "builtin-queue", "gateway", "receive", "driver"] }
symphonia = { features = ["aac", "mp3", "isomp4", "alac", "symphonia-format-isomp4"], version = "0.5.4" }
dashmap = "6.0.1"
url = "2.5.2"
dirs = "5.0.1"
sea-orm = { version = "1.1.0-rc.1", features = ["sqlx-sqlite", "sqlx-postgres", "runtime-tokio-rustls"] }
sea-orm-migration = { version = "1.1.0-rc.1" }
percent-encoding = "2.3.1"
serde_urlencoded = "0.7.1"
poem = { version = "3.0.4" }
async-graphql-poem = { version = "7.0.7" }
async-graphql = { version = "7.0.7", features = ["decimal", "chrono", "dataloader", "dynamic-schema"] }
dotenvy = "0.15.7"
lazy_static = { version = "1.5.0" }
seaography = "1.1.0-rc.1"
catbox = "0.8.2"
tempfile = "3.12.0"
rusty_ytdl = { version = "0.7.4", features = ["rustls-tls"] }
either = "1.13.0"
anyhow = "1.0.86"
thiserror = "1.0.63"

[build-dependencies]
tonic-build = "0.12.1"
cynic-codegen = { version = "3.7.3" }

[profile.dev]
codegen-units = 512
debug = 2

[profile.release]
lto = true
strip = "symbols"

[[bin]]
name = "kasuki"
path = "src/main.rs"
