array_width = 80
attr_fn_like_width = 80
brace_style = "PreferSameLine"
condense_wildcard_suffixes = true
edition = "2021"
fn_args_layout = "Compressed"
fn_params_layout = "Compressed"
hard_tabs = true
match_block_trailing_comma = true
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_try_shorthand = true
