name: Build & Publish Release Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Prepare publish
        run: |
          mkdir build
          cp target/release/kasuki build/
          cp config.example.toml build/config.toml
          cp readme.md build/readme.md
          cp LICENSE build/LICENSE
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'build/kasuki'

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Release ${{ github.sha }}
          body: |
            Release ${{ github.sha }}
            - [kasuki](kasuki)
            - [config.toml](config.toml)
            - [readme.md](readme.md)
            - [LICENSE](LICENSE)
          tag_name: ${{ github.sha }}
          draft: false
          prerelease: false