name: Build & Publish caddy Docker Images

on:
  push:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: "caddy"
  cancel-in-progress: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push amd64
        id: docker_build_amd64
        uses: docker/build-push-action@v5
        with:
          context: ./caddy
          file: ./caddy/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/caddy:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
