name: Build & Publish Release Dev Image

on:
  push:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: "dev"
  cancel-in-progress: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::$
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/i386,linux/arm/v7,linux/arm/v6
          tags: valgul/kasuki:dev
