name: Linting project

on:
  pull_request:
    branches:
      - master
permissions:
  contents: none
  pull-requests: write
  issues: write
  packages: none
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name : Adding clippy
        run: rustup component add clippy
      - name: Lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features