name: Rust Clippy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
      checks: write

concurrency:
  group: "clippy"
  cancel-in-progress: false

jobs:
  linter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy

    - name: Run Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: -- -D warnings