name: Build & Publish Dev Build

on:
  push:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: "dev_build"
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract version
        id: extract
        run: |
          echo "::set-output name=version::$(grep -oP 'VERSION: \K\".*\"' version.rs)-dev"
      - name: Setup Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Build
        run: cargo build --verbose
      - name: Create Git tag
        run: git tag v${{ steps.extract.outputs.version }}
      - name: Push Git tag
        run: git push origin v${{ steps.extract.outputs.version }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract.outputs.version }}
          release_name: Dev ${{ steps.extract.outputs.version }}
          draft: false
          prerelease: true
