name: test and lint
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Configure protoc for proto3 optional fields
        run: echo "syntax = \"proto3\"; option allow_proto3_optional = true;" >.protoconfig

      - name: Set environment variable for protoc
        run: export PROTO_CONFIG_PATH=.protoconfig

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --workspace --tests

      - name: Run tests
        run: cargo test --workspace

      - name: Run fmt
        run: cargo fmt --all -- --check
